### ISSUE TITLE
Offset Issues using Waveshare RP2040-LCD_0.69

### ISSUE THREAD

**Issue by mindforger** [adafruit/Adafruit_CircuitPython_ST7735R#28]
Using the Waveshare RP2040 Pi Pico clone with integrated ST7735S based 0.69 160x80 RGB display

i got the following offset issues with my display
![photo5453947621233245222](https://user-images.githubusercontent.com/2683555/167243423-4b399a05-1579-4b37-ac76-4239938bb0fc.jpg)
![photo5453947621233245221](https://user-images.githubusercontent.com/2683555/167243424-113b2c3f-e19a-4af6-ae0c-7fa6d72fc200.jpg)
a 26 pixel offset from the "top" and 1 pixel offest from the "right" (having the usb connector on the right)

i can set the display to 106 instead of 80 pixel and it perfectly connects at the top but at the bottom i have invisible screen (around 2 lines of terminal space)

`
import board, displayio, digitalio, busio, time
from st7735r import ST7735R

lcd_dc = board.GP8
lcd_cs = board.GP9
lcd_clk = board.GP10
lcd_din = board.GP11
lcd_rst = board.GP12
lcd_bl = board.GP25

displayio.release_displays()
backlight = digitalio.DigitalInOut(lcd_bl)
lcd_spi = busio.SPI(clock=lcd_clk, MOSI=lcd_din)
lcd_bus = displayio.FourWire(lcd_spi, command=lcd_dc, chip_select=lcd_cs, reset=lcd_rst)
display = ST7735R(lcd_bus, width=80, height=160, invert=True)
display.rotation=90
`

there is this other repo i did not try out because their code is so overblown compared to yours but they provide offset options

https://github.com/adafruit/Adafruit_CircuitPython_RGB_Display/blob/main/adafruit_rgb_display/st7735.py

i am not sure if their driver is better, but looking on all that required additional code and dependencies i don't want to use it

**Comment by mindforger** [comment]
nevermind looking up displayio.Display.__init__ i found i can throw additional parameters to the ST7735R construction

`
display = ST7735R(lcd_bus, width=80, height=160, invert=True, colstart=26, rowstart=1)
`

**Comment by mindforger** [comment]
just for giggles and more usefull stuff

added brightness pin
made it only 10% bright
unfortunately when the program ends without releasing the display the brightness jumps back to 100%

```
import board, displayio, digitalio, busio, time
from st7735r import ST7735R

lcd_dc = board.GP8
lcd_cs = board.GP9
lcd_clk = board.GP10
lcd_din = board.GP11
lcd_rst = board.GP12
lcd_bl = board.GP25

displayio.release_displays()
lcd_spi = busio.SPI(clock=lcd_clk, MOSI=lcd_din)
lcd_bus = displayio.FourWire(lcd_spi, command=lcd_dc, chip_select=lcd_cs, reset=lcd_rst)
display = ST7735R(lcd_bus, width=160, height=80, invert=True, colstart=26, rowstart=1, rotation=90, backlight_pin=lcd_bl, auto_brightness=False, brightness=0.1)
print("this is working")
time.sleep(2)

```

**Comment by makermelissa** [comment]
Yep, we usually make examples for each of our displays with the correct offsets and often waveshare is usually similar enough to one of them. I actually really like the way that CircuitPython allows the offsets in the initializer over the way we do it in Arduino.
