### ISSUE TITLE
Driver not working on tft spi 1.8in lcd display

### ISSUE THREAD

**Issue by anonfaded** [adafruit/Adafruit_CircuitPython_ST7735R#37]
There is a s variant of this driver with same name but a s in the end so can you guide on how to make it work? Right now my lcd isn't working and the code runs with no errors, for reference and complete details about my issue please read this: https://github.com/adafruit/circuitpython/issues/9223

**Comment by dhalbert** [comment]
See https://github.com/adafruit/circuitpython/issues/9223#issuecomment-2096268940. Not a library issue.
