### ISSUE TITLE
Problems with ST7735R for Displayio

### ISSUE THREAD

**Issue by hulkco** [adafruit/Adafruit_CircuitPython_ST7735R#7]
I have several days trying to make this cheap screen work, with the new native driver "displayio".
But I have not been successful.
This same screen very well with the drivers for Arduino (Adafruit_GFX.h and Adafruit_ST7735.h, I have only made a small change to show the colors correctly).
It also works correctly with the ST7737.py driver from the adafruit_rgb_display library, where I also made a small change for the colors.
I add the code that I am using and a screen that is shown from time to time when executing the program.

```"""
This example will test out the display on the Mini TFT Breakout
"""
import board
import displayio
from adafruit_st7735r import ST7735R

spi = board.SPI()
tft_cs = board.D10
tft_dc = board.D3
rst = board.D2

displayio.release_displays()
display_bus = displayio.FourWire(spi, command=tft_dc, chip_select=tft_cs, reset=rst)
display = ST7735R(display_bus, width=160, height=80, colstart=24, rotation=180, bgr=True)
'''
Make the display context
'''
splash = displayio.Group(max_size=10)
display.show(splash)

color_bitmap = displayio.Bitmap(160, 80, 1)
color_palette = displayio.Palette(1)
color_palette[0] = 0xFF0000 #   red

bg_sprite = displayio.TileGrid(color_bitmap,
                               pixel_shader=color_palette,
                               x=0, y=0)
splash.append(bg_sprite)

while True:
    pass
```
![Bast_Displayio](https://user-images.githubusercontent.com/16407513/60541578-21c17280-9ccf-11e9-8eeb-41cd2f6abd60.jpg)

**Comment by makermelissa** [comment]
Could yo try it with https://github.com/adafruit/Adafruit_CircuitPython_ST7735 and see if you get any better results?

**Comment by hulkco** [comment]
Yes @makermelissa, I have tried, but without success.

**Comment by makermelissa** [comment]
Ok, it probably uses a different set of init commands that the adafruit displays. Unfortunately I don't have one of those to test with. Since you got it working with the RGB display library, maybe you could narrow down which init command is different?

**Comment by hulkco** [comment]
apparently they are something different.
![Selection_062](https://user-images.githubusercontent.com/16407513/60544309-c050d200-9cd5-11e9-9990-2ab20813c31f.png)

**Comment by makermelissa** [comment]
Yeah, the main difference is the RGB Display library does all of the processing in CircuitPython script and the displayio one does most of the processing from within CircuitPython itself. However, the init sequences sent to the display itself should be the same.

**Comment by hulkco** [comment]
I'm going to play a little in this section, I hope to achieve something, thanks!

**Comment by hulkco** [comment]
Hello @makermelissa, do you know where I can find information on how to create drivers for circuitpython?

**Comment by makermelissa** [comment]
Yeah, you might like this guide: https://learn.adafruit.com/creating-and-sharing-a-circuitpython-library. It's more of a general library guide though.

With regards to the displayio libraries though, those are mostly the init sequences that are passed into CircuitPython and the init function. I was reading through the CP source code to figure some of it out, sometimes referencing the arduino libraries, etc. That's why I referred you to the RGB_Display library since you said the sequence was working. Also, sometimes putting a delay in can help.

Oh, one more thing I just thought of is to look at the examples included with this driver as it shows different parameters you can pass in to affect the driver without rewriting it.

**Comment by hulkco** [comment]
Thank you! I will read it with pleasure!

**Comment by makermelissa** [comment]
For displayio, you may also like: https://learn.adafruit.com/circuitpython-display-support-using-displayio and https://learn.adafruit.com/using-circuitpython-displayio-with-a-tft-featherwing

**Comment by hulkco** [comment]
Thanks again!!

**Comment by hulkco** [comment]
Hi, I have solved the problem, changing the following values.
```
Original
b"\x20\x00" # _INVOFF
b"\x36\x01\x18" # _MADCTL bottom to top refresh
Changes
b"\x21\x00" # _INVON
b"\x36\x01\x08" # _MADCTL bottom to top refresh

```
Thanks to [Robotron](https://www.rototron.info/circuitpython-nrf52840-lcd-displays-tutorial/) for his fantastic tutorial !!

![Selection_083](https://user-images.githubusercontent.com/16407513/60690130-fd59c780-9e81-11e9-96b6-b1917e006553.png)

**Comment by makermelissa** [comment]
Nice! Thanks for the link and your solution. I hadn’t seen those tutorials. Looks like it was created around the same time I was adding a bunch of the drivers.

**Comment by tannewt** [comment]
@hulkco where did you get this display? I think we likely want to add kwargs to the constructor to handle these differences.

**Comment by makermelissa** [comment]
Probably something like https://www.amazon.com/WINGONEER-80x160-Display-Screen-Arduino/dp/B07QB6BCLP/ref=sr_1_6

**Comment by hulkco** [comment]
Hello @tannewt , buy the breakout board [here](https://www.aliexpress.com/item/32857836858.html?spm=a2g0s.9042311.0.0.66764c4dyEojjR), also buy only [screen](https://www.aliexpress.com/item/32857824664.html?spm=a2g0s.9042311.0.0.3f554c4dV3x8vb), since the project that I have is to create a Board compatible with Circuitpython, but they are quite common, just put in the aliexpres search engine 0.96 LCD.
Regards!

**Comment by tannewt** [comment]
Thanks @hulkco! Looks like it is a ST7735 so that driver should be updated.
